export enum eDispatchType {
	LOGIN = 'LOGIN',
	REGISTER = 'REGISTER',
	LOGOUT = 'LOGOUT',
	ADD_PROJECT_PREVIEW = 'ADD_PROJECT_PREVIEW',
	CLEAR_PROJECT_PREVIEW = 'CLEAR_PROJECT_PREVIEW',
	ADD_IMPACT_ASSESSMENT_METHOD = 'ADD_IMPACT_ASSESSMENT_METHOD',
	SET_IMPACT_CATEGORY = 'SET_IMPACT_CATEGORY',
	UPDATE_PROFILE = 'UPDATE_PROFILE',
	ADD_DELETE_PROCESSES_IDS = 'ADD_DELETE_PROCESSES_IDS',
	CLEAR_DELETE_PROCESSES_IDS = 'CLEAR_DELETE_PROCESSES_IDS',
	SELECT_CHECKBOX = 'SELECT_CHECKBOX',
	CLEAR_SELECT_CHECKBOX = 'CLEAR_SELECT_CHECKBOX',
	SELECT_ALL_CHECKBOX = 'SELECT_ALL_CHECKBOX',
	CLOSE_CHECKBOX = 'CLOSE_CHECKBOX',
	UPDATE_ORGANIZATION_ID = 'UPDATE_ORGANIZATION_ID',
}

export enum ToolboxDispatchType {
	LOADING_TOOLBOX = 'LOADING_TOOLBOX',
	TRIGGER_MENU = 'TRIGGER_MENU',
	ADD_TRIGGER_ID = 'ADD_TRIGGER_ID',
	CLEAR_TRIGGER_IDS = 'CLEAR_TRIGGER_IDS',
	ADD_MENU_ID = 'ADD_MENU_ID',
	SELECTED_TRIGGER_ID = 'SELECTED_TRIGGER_ID',
	CLEAR_SELECTED_TRIGGER_ID = 'CLEAR_SELECTED_TRIGGER_ID',
}

export enum ContextDispatch {
	SET_CONTEXT_MENU = 'SET_CONTEXT_MENU',
	CLEAR_CONTEXT_MENU = 'CLEAR_CONTEXT_MENU',
	CLOSE_CONTEXT_MENU = 'CLOSE_CONTEXT_MENU',
}

export enum SheetBarDispatch {
	SET_NODE = 'SET_NODE',
	REMOVE_NODE = 'REMOVE_NODE',
	MODIFY_QUERY_PARAMS = 'MODIFY_QUERY_PARAMS',
	SET_EXCHANGE = 'SET_EXCHANGE',
}

export enum PlaygroundDispatch {
	SET_IMPACT_METHOD = 'SET_IMPACT_METHOD',
	SET_IMPACT_CATEGORY = 'SET_IMPACT_CATEGORY',
	REMOVE_IMPACT_METHOD = 'REMOVE_IMPACT_METHOD',
	SET_PROJECT_INFOR = 'SET_PROJECT_INFOR',
	ADDING_NOTE = 'ADDING_NOTE',
	DONE_ADDING_NOTE = 'DONE_ADDING_NOTE',
}
export enum PlaygroundControlDispatch {
	SELECTED_TRIGGER_ID = 'SELECTED_TRIGGER_ID',
	CLEAR_TRIGGER_IDS = 'CLEAR_TRIGGER_IDS',
	ADD_MENU_ID = 'ADD_MENU_ID',
	ADD_TRIGGER_ID = 'ADD_TRIGGER_ID',
	ADD_CALCULATED_DATA = 'ADD_CALCULATED_DATA',
	TRIGGER_MINIMIZE = 'TRIGGER_MINIMIZE',
}
