export enum eDispatchType {
	LOGIN = 'LOGIN',
	REGISTER = 'REGISTER',
	LOGOUT = 'LOGOUT',
	ADD_PROJECT_PREVIEW = 'ADD_PROJECT_PREVIEW',
	CLEAR_PROJECT_PREVIEW = 'CLEAR_PROJECT_PREVIEW',
	ADD_IMPACT_ASSESSMENT_METHOD = 'ADD_IMPACT_ASSESSMENT_METHOD',
}
